package setawatch.game;

public enum PhaseStep {
    START_PHASE,
    END_PHASE,

    SETUP_CHOOSE_ADVENTURERS,

    CAMP_CHOOSE_PLAYER,
    CAMP_ASSIGN_DICE,
    CAMP_HEAL_CHOOSE_ABILITY_CARD,

    WATCH_REVEAL_CREATURES,
    WATCH_ASSIGN_DICE,

    WATCH_REVEAL_CREATURES_EXHAUST_ADVENTURER_ABILITY,
    WATCH_REVEAL_CREATURES_STEAL_DIE
}
