package setawatch.game;

public enum PhaseStep {
    START_PHASE,
    END_PHASE,

    SETUP_CHOOSE_ADVENTURERS,

    CAMP_CHOOSE_PLAYER,
    CAMP_ASSIGN_DICE,

    WATCH_REVEAL_CREATURES,
    WATCH_ASSIGN_DICE
}
